version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8080:8000"
    volumes:
      - ./server:/server
  client:
    build: ./client
    environment:
      WDS_SOCKET_PORT: 3030
    ports:
      - "3030:3000"
    volumes:
      - ./client/src:/client/src
    depends_on:
      - server
